/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionArray: typeof import('./components/AccordionArray.vue')['default']
    Breadcrumbs: typeof import('./components/Breadcrumbs.vue')['default']
    CampaignEditor: typeof import('./views/CampaignEditor.vue')['default']
    CampaignList: typeof import('./views/CampaignList.vue')['default']
    ClassSelector: typeof import('./components/ClassSelector.vue')['default']
    FormSpecNode: typeof import('./components/FormSpecNode.vue')['default']
    IonAccordion: typeof import('@ionic/vue')['IonAccordion']
    IonAccordionGroup: typeof import('@ionic/vue')['IonAccordionGroup']
    IonBadge: typeof import('@ionic/vue')['IonBadge']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonFooter: typeof import('@ionic/vue')['IonFooter']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonicAccordionArray: typeof import('./components/IonicAccordionArray.vue')['default']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonModal: typeof import('@ionic/vue')['IonModal']
    IonNote: typeof import('@ionic/vue')['IonNote']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRange: typeof import('@ionic/vue')['IonRange']
    IonText: typeof import('@ionic/vue')['IonText']
    IonTextarea: typeof import('@ionic/vue')['IonTextarea']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    PartyEditor: typeof import('./views/PartyEditor.vue')['default']
    PlayerCharacterEdit: typeof import('./views/PlayerCharacterEdit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
